name: Tests
on:
  push:
    branches:
      - main
    paths:
      - "random-emoji-api/**"
  pull_request:
    branches: ["*"]
    paths:
      - "random-emoji-api/**"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test:e2e
